---
- name: "Write configuration to qBittorrent.conf : {{ section.name }}"
  become: true
  community.general.ini_file:
    path: "{{ qbittorrent_conf_copy.dest }}"
    section: "{{ section.name }}"
    option: "{{ option.name }}"
    value: "{{ option.value }}"
    mode: "0640"
    no_extra_spaces: true
  loop: "{{ section.options | dict2items(key_name='name') }}"
  loop_control:
    loop_var: option
  notify: Config file changed
