---
- name: Ensure configuration directory exists
  become: true
  ansible.builtin.file:
    path: "{{ qbittorrent_data_dir }}/qBittorrent/config"
    state: directory
    owner: "{{ qbittorrent_user }}"
    group: "{{ qbittorrent_group }}"
    mode: "0755"

- name: Compile configuration dictionary
  ansible.builtin.set_fact:
    _qbittorrent_config: "{{ qbittorrent_config | default({}) | combine(_config_override, recursive=True) }}"
  vars:
    _config_override:
      LegalNotice:
        Accepted: "true"
      Preferences:
        WebUI\Port: "{{ qbittorrent_webui_port }}"

- name: Make sure configuration file exists
  become: true
  ansible.builtin.file:
    path: "{{ qbittorrent_conf_file }}"
    state: touch
    owner: "{{ 'root' if qbittorrent_config_read_only else qbittorrent_user }}"
    group: "{{ qbittorrent_group }}"
    mode: "0640" # For some reason qBittorrent uses 644, so if the config isn't readonly this task will pretty much always end up as `changed`

- name: Make backup of the configuration file
  become: true
  ansible.builtin.copy:
    src: "{{ qbittorrent_conf_file }}"
    dest: "{{ qbittorrent_conf_file }}.bak"
    remote_src: true
    mode: "0600"

# Make a temporary configuration file we can edit.
# Otheriwse qbt will overwrite it when stopped.
# We can't write to the one qBittorrent.conf directly either.
# because it might be overwritten while we're editing it.
# We want to restart the service only if the config has changed.
# so stopping it just to write the configuration isn't an option.
- name: Make temporary configuration file to edit
  become: true
  ansible.builtin.copy:
    src: "{{ qbittorrent_conf_file }}"
    dest: "{{ qbittorrent_conf_file }}.tmp"
    remote_src: true
    mode: "0600"
  register: qbittorrent_conf_copy

# Populate this temporary copy with the settings
- name: Write configuration file
  ansible.builtin.include_tasks:
    file: configuration_file.yml
  loop: "{{ _qbittorrent_config | dict2items(key_name='name', value_name='options') }}"
  loop_control:
    loop_var: section
